-- TPP Migration: tpp_documents
-- Documents uploaded by clients or generated by AI, linked to cases

CREATE TABLE IF NOT EXISTS tpp_documents (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id         UUID REFERENCES tpp_cases(id) ON DELETE CASCADE,
  client_id       UUID NOT NULL REFERENCES client_profiles(id) ON DELETE CASCADE,
  legal_doc_id    UUID REFERENCES documents(id) ON DELETE SET NULL, -- link to legal-portal docs table
  display_name    TEXT NOT NULL,
  storage_path    TEXT,                -- Supabase Storage path
  file_type       TEXT,                -- MIME type
  file_size_bytes BIGINT,
  source          TEXT NOT NULL DEFAULT 'user'
                  CHECK (source IN ('user', 'ai_generated', 'lawyer')),
  created_at      TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX tpp_documents_case_id_idx ON tpp_documents(case_id);
CREATE INDEX tpp_documents_client_id_idx ON tpp_documents(client_id);
CREATE INDEX tpp_documents_created_at_idx ON tpp_documents(created_at DESC);

-- RLS
ALTER TABLE tpp_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tpp_documents: client sees own docs"
  ON tpp_documents FOR SELECT
  USING (client_id = auth.uid());

CREATE POLICY "tpp_documents: lawyer sees case docs"
  ON tpp_documents FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM tpp_cases c
      WHERE c.id = case_id AND c.lawyer_id = auth.uid()
    )
  );

CREATE POLICY "tpp_documents: client inserts own docs"
  ON tpp_documents FOR INSERT
  WITH CHECK (client_id = auth.uid());

CREATE POLICY "tpp_documents: client deletes own docs"
  ON tpp_documents FOR DELETE
  USING (client_id = auth.uid());

CREATE POLICY "tpp_documents: service role full access"
  ON tpp_documents FOR ALL
  USING (auth.role() = 'service_role');
